### ISSUE TITLE
Change "cohort" to "section" (Rails data model)

### ISSUE THREAD

**Issue by a6ftcruton** [turingschool-projects/skill-inventory-rails#33]

**Comment by a6ftcruton** [comment]
(DONT change the name from group--module is reserved and was a huge headache)

DO change the title--instead of group name, it should be a number (integer)
Do we want to keep the data as string data? (e.g. "1") --> probably not?

-Validate data as inclusion: { in: ["1", "2", "3", "4"] }  
  OR as a range of numbers:  inclusion: { in: [1..4] }

**Comment by ianderse** [comment]
problem is, how does this affect the ember side? We should all sit down and talk about how the data is getting passed back and forth. It depends on how we set up the ember data I think, but still hazy on that.
